<a href="https://colab.research.google.com/github/jooharver/Machine-Learning/blob/main/ML_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
def norm_data(data):
  '''
  Melakukan normalisasi data

  Parameters:
    data(list) : Data yang akan dinormalisasi

  Returns:
    data(list) : Data hasil normalisasi
  '''

  data_min = min(data)
  data_max = max(data)
  data_len = len(data)

  for i in range(0, data_len):
    data[i] = (data[i] - data_min) / (data_max - data_min)

  return data

#Contoh penggunaan
data = [10,11,12,14,16]
n_data = norm_data(data) #melakukan normalisasi
print(n_data)


[0.0, 0.16666666666666666, 0.3333333333333333, 0.6666666666666666, 1.0]


In [2]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

np.set_printoptions(precision=6) #bulatkan 4 angka koma
np.set_printoptions(suppress=True) #hilangkan nilai e

#membentuk data
#Hal ini dikarenakan scikit-learn hanya menerima input
#dalam bentuk n-dimensional array

data = [
        [100, 0.0001],
        [50, 0.05],
        [30, 0.003],
       ]

#ubah ke bentuk umpy n-dimensional array
data = np.asarray(data)
print ('Data Asli')
print(data)

#Mendefinisikan obyek MinMaxScaler
scaler = MinMaxScaler()
#Transformasikan data
scaled = scaler.fit_transform(data)
print ('Data Normalisasi')
print(scaled)

Data Asli
[[100.       0.0001]
 [ 50.       0.05  ]
 [ 30.       0.003 ]]
Data Normalisasi
[[1.       0.      ]
 [0.285714 1.      ]
 [0.       0.058116]]


In [3]:
import numpy as np
from sklearn.preprocessing import StandardScaler

np.set_printoptions(precision=6) #bulatkan 4 angka koma
np.set_printoptions(suppress=True) #hilangkan nilai e

#membentuk data
#Hal ini dikarenakan scikit-learn hanya menerima input
#dalam bentuk n-dimensional array

data = [
        [100, 0.0001],
        [50, 0.05],
        [30, 0.003],
       ]

#ubah ke bentuk umpy n-dimensional array
data = np.asarray(data)
print ('Data Asli')
print(data)

#Mendefinisikan obyek MinMaxScaler
scaler = StandardScaler()
#Transformasikan data
scaled = scaler.fit_transform(data)
print ('Data Normalisasi')
print(scaled)



Data Asli
[[100.       0.0001]
 [ 50.       0.05  ]
 [ 30.       0.003 ]]
Data Normalisasi
[[ 1.358732 -0.76956 ]
 [-0.339683  1.412317]
 [-1.019049 -0.642757]]


In [4]:
from sklearn.preprocessing import OrdinalEncoder

#Inisialisasi obyek ordinal encoder
oe = OrdinalEncoder()

#Definisikan data
#dalam bentuk 2d

data = [
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarta'],
    ['Politeknik Negeri Semarang']
]

#Transformasi ordinal encoder
transform_oe = oe.fit_transform(data)

print('Data Asli')
print(data)

print('Data Transformasi Ordinal Encoder')
print(transform_oe)

Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarta'], ['Politeknik Negeri Semarang']]
Data Transformasi Ordinal Encoder
[[2.]
 [0.]
 [1.]
 [3.]]
